<a href="https://colab.research.google.com/github/jlcalleu18/MicroCredential-DataAnalytics/blob/main/Day_5_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Intro to numpy

In [ ]:
import numpy as np

In [ ]:
np_city = np.array(['NYC', 'LA', 'Maimi', 'Houston'])

In [ ]:
np_city.shape

(4,)

In [ ]:
np_city.size

4

In [ ]:
np_city2 = np.array([['NYC', 'LA', 'Maimi', 'Houston'], 
                     ['NY', 'CA','FL','TX']])

In [ ]:
np_city2.shape

(2, 4)

In [ ]:
np_city2.size

8

In [ ]:
np_city2.dtype

dtype('<U7')

In [ ]:
## Create a np array with 5 lists in it... 
## each list must have 10 items in it

In [ ]:
np_objects = np.array([['red', 'black', 'blue', 'green', 'yellow', 'white', 'pick', 'orange', 'brown','golden'], 
                      ['Avocado','banana','Blackberries','Blueberries','Breadfruit','Cantaloupe','Carambola','Cherimoya','Cherries','Apple'],
                       ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I','J'],
                       ['red', 'black', 'blue', 'green', 'yellow', 'white', 'pick', 'orange', 'brown','golden'],
                       ['red', 'black', 'blue', 'green', 'yellow', 'white', 'pick', 'orange', 'brown','golden'],])

In [ ]:
np_objects.shape

(5, 10)

In [ ]:
np_objects.size

50

In [ ]:
first_trial_cyclist = [10,23,34,54,65,45,34,23]

In [ ]:
second_trial_cyclist = [11,12,22,34,54,45,56,78]

In [ ]:
np_first_trial = np.array(first_trial_cyclist)
np_second_trial = np.array(second_trial_cyclist)

In [ ]:
np_first_trial + np_second_trial

array([ 21,  35,  56,  88, 119,  90,  90, 101])

In [ ]:
cyclist_trial = np.array([[10,25,27,34],[12,11,21,23]])

In [ ]:
ftrial = cyclist_trial[0]

In [ ]:
ftrial

array([10, 25, 27, 34])

In [ ]:
newList = ['string1', 'string2']

In [ ]:
newList[0]

'string1'

In [ ]:
newList[0][2]

'r'

In [ ]:
strial = cyclist_trial[1]

In [ ]:
strial

array([12, 11, 21, 23])

In [ ]:
ftrial[1]

25

In [ ]:
cyclist_trial[0][1]

25

In [ ]:
test_score = np.array([[83,71,67,63],[54,68,81,45]])

In [ ]:
passed = test_score >60

In [ ]:
passed

array([[ True,  True,  True,  True],
       [False,  True,  True, False]])

In [ ]:
test_score2 = test_score

In [ ]:
test_score is test_score2

True

In [ ]:
NYC_Boroughs = np.array(['Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Staten Island'])

In [ ]:
NYC_Boroughs

array(['Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Staten Island'],
      dtype='<U13')

In [ ]:
NY_Boroughs = NYC_Boroughs.view()
#view is not copy everything

In [ ]:
len(NY_Boroughs)

5

In [ ]:
NY_Boroughs[4]  = 'Central Park'

In [ ]:
len(NYC_Boroughs)

5

In [ ]:
NY_Boroughs

array(['Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Central Park'],
      dtype='<U13')

In [ ]:
NYC_Boroughs is NY_Boroughs

False

In [ ]:
NYC = NYC_Boroughs.copy()

In [ ]:
NYC is NYC_Boroughs

False

In [ ]:
NYC

array(['Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Central Park'],
      dtype='<U13')

In [ ]:
NYC[4] = 'Astoria'

In [ ]:
NYC_Boroughs

array(['Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Central Park'],
      dtype='<U13')